### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ziriax** [alexeyraspopov/react-coroutine#8]
This seems like a fantastic project, but it seems not very active. 

Does anyone know alternatives to this, or is this project just rock stable? :)

**Comment by alexeyraspopov** [comment]
This project is not dead. I have a bunch of projects using it. There is no significant ways for improvements or features. The library does what it suppose to.

Due to the difference in implementation, approach, and ideas, react-coroutine won't work with React Hooks. You may want to switch to hooks completely as it's the future of React development.
